# Site settings
title: SEN Tutors | Special Needs Tuition | Eva Coates
tagline: Experienced SEN Tutoring Services | Individual Learning Support for Special Educational Needs
email: ewa.coates@gmail.com
url: https://www.sen-tutor.co.uk
author: Ewa Coates
locale: en-GB
description: "Discover SEN Tutoring Services. Specialized, one-on-one support to enhance learning for children with SEN. Expert tutors, personalized strategies."
keywords: "SEN Tutoring,SEN Learning Strategies,SEN Tutoring Services,SEN Curriculum Support,SEN Teaching Techniques,Private SEN Tutors,One-on-One SEN Tutoring"
meta_author: Ewa Coates

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Build settings
markdown: kramdown
permalink: pretty

sass:
  style: expanded

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""

plugins:
  - jekyll-seo-tag
